### ISSUE TITLE
Error en implementación

### ISSUE THREAD

**Issue by matias89** [Alvacampos/MyCv#1]
https://github.com/Alvacampos/MyCv/blob/110448f0684bd4c8917a87dd434a1725023eed50/Js/register.js#L1

Fijate que de la linea 1 a la 6 estás accediendo a los values y luego le agregas el listener. Estás constantes siempre van a tener el valor por defecto, que es el vacio. Esto lo podés arreglar moviendo todas estás lineas que te mencioné dentro del addEventListener, para que al momento del click recién acceda al valor actual, y no a los valores por defecto como ahora, que nunca van a cambiar.

**Comment by matias89** [comment]
`const button1=document.getElementById("reg");
button1.addEventListener("click", function(){
let name = document.getElementById("name").value;
let lname=document.getElementById("lname").value;
let mail=document.getElementById("mail").value;
let bday=document.getElementById("bday").value;
let nat=document.getElementById("nat").value;
	alert("Thank You."+
    "\nName: " +name +
    "\nLast Name: " + lname+
    "\nMail:  "+ mail+
    "\nBirthday: " + bday + 
    "\nNationality: " + nat);   
});`

**Comment by matias89** [comment]
Te recomiendo también que cuando uses variables en strings, lo hagas con templates strings, por ejemplo:
```javascript
const message = `Thank you ${name} ${lname} blablabla`;
alert(message);
```

**Comment by Alvacampos** [comment]
Gracias!
